project:
  type: website
  lib-dir: site_libs
  render:
    - index.qmd
    - slides/*.qmd

execute:
  freeze: auto

editor: source

website:
  title: "MICOM EpiData Workshop 2025"
  page-footer:
    left: "This work by the [Delphi Research Group](https://delphi.cmu.edu) is licensed under the [MIT license](LICENSE.md)."
    right: "Supported in part by the [CSTE](https://www.cste.org) and the [CDC](https://www.cdc.gov)."
  navbar:
    pinned: false
    title: "<i class='bi bi-graph-down'></i> MICOM Workshop 2025"
    right:
      - text: Delphi
        url: https://delphi.cmu.edu/
      - text: GitHub
        url: https://github.com/cmu-delphi/micom-tooling-workshop-2025
        icon: github


format:
  html:
    theme: [cosmo, assets/styles.scss]
    page-layout: custom
